"""Import admin route callables once for registration."""

from app.api.routes.admin import (
    handle_admin_approve_charge,
    handle_admin_approve_receipt,
    handle_admin_approve_vip_order,
    handle_admin_broadcast,
    handle_admin_deny_charge,
    handle_admin_deny_receipt,
    handle_admin_deny_vip_order,
    handle_admin_get_charge_packages,
    handle_admin_get_job_schedules,
    handle_admin_get_payment_settings,
    handle_admin_get_plans,
    handle_admin_get_support_settings,
    handle_admin_ip_whitelist_get,
    handle_admin_ip_whitelist_update,
    handle_admin_logs,
    handle_admin_pending_receipts,
    handle_admin_receipt_detail,
    handle_admin_arcade_flags,
    handle_admin_recent_broadcasts,
    handle_admin_remove_vip,
    handle_admin_reset_arcade,
    handle_admin_search_user_for_vip,
    handle_admin_send_notification,
    handle_admin_servers,
    handle_admin_set_vip,
    handle_admin_stats,
    handle_admin_subscription_delete,
    handle_admin_subscription_extend,
    handle_admin_subscription_usage,
    handle_admin_subscriptions,
    handle_admin_ticket_archive,
    handle_admin_ticket_close,
    handle_admin_ticket_delete,
    handle_admin_ticket_detail,
    handle_admin_ticket_reopen,
    handle_admin_ticket_photo_get,
    handle_admin_ticket_photo_upload,
    handle_admin_ticket_reply,
    handle_admin_tickets,
    handle_admin_toggle_user,
    handle_admin_update_charge_packages,
    handle_admin_update_job_schedules,
    handle_admin_update_payment_settings,
    handle_admin_update_plans,
    handle_admin_user_delete,
    handle_admin_user_detail,
    handle_admin_user_update,
    handle_admin_users,
    handle_admin_vip_users,
)
from app.api.routes.admin_auth import (
    handle_admin_login,
    handle_admin_logout,
    handle_admin_session_revoke,
    handle_admin_sessions_list,
    handle_admin_sessions_revoke_others,
    handle_admin_verify_2fa,
    handle_admin_verify_session,
)
from app.api.routes.admin_db import (
    handle_admin_db_capabilities,
    handle_admin_db_exec,
    handle_admin_db_query,
    handle_admin_db_table_rows,
    handle_admin_db_table_schema,
    handle_admin_db_tables,
)
from app.api.routes.admin_ui import (
    handle_admin_ui_get_settings,
    handle_admin_ui_set_settings,
    handle_admin_ui_upload_background,
)
from app.api.routes.admin_ws import handle_admin_support_ws
